---

- name: Deploy memcached
  k8s:
    definition: "{{ lookup('template', item) }}"
    wait: yes
  loop:
  - deployment-memcached.yaml.j2
  - service-memcached.yaml.j2

- name: Wait for memcached to become Ready
  k8s_info:
    kind: Pod
    label_selectors:
    - name = memcached
    namespace: "{{ stack_namespace }}"
  register: memcached_result
  until: >-
    memcached_result.resources is defined
    and memcached_result.resources|length == 1
    and memcached_result.resources[0].status is defined
    and memcached_result.resources[0].status.containerStatuses is defined
    and memcached_result.resources[0].status.containerStatuses|length == 1
    and memcached_result.resources[0].status.containerStatuses[0].ready
  delay: 10
  retries: "{{ (wait_timeout|int / 10)|int }}"
