---

# To 'shutdown' we remove: -
# - Stack
# - Django secret
# And then, delete: -
# - Media volume (optional)

- name: Set django secret fact
  # These facts are required to remove the secret...
  set_fact:
    stack_django_secret_key_fact: '{{ stack_django_secret_key }}'
    stack_django_superuser_password_fact: '{{ stack_django_superuser_password }}'

- name: Shutdown stack
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    state: absent
  loop:
  - statefulset-stack
  - statefulset-worker
  - deployment-beat
  - secret-django

- name: Wait for stack to disappear
  k8s_info:
    kind: Pod
    name: stack-0
    namespace: "{{ stack_namespace }}"
  register: stack_result
  until: stack_result.resources|length == 0
  delay: 5
  retries: "{{ (wait_timeout|int / 5)|int }}"

- name: Wait for worker to disappear
  k8s_info:
    kind: Pod
    name: worker-0
    namespace: "{{ stack_namespace }}"
  register: worker_result
  until: worker_result.resources|length == 0
  delay: 5
  retries: "{{ (wait_timeout|int / 5)|int }}"

- name: Remove media volume
  k8s:
    definition: "{{ lookup('template', 'pvc-media.yaml.j2') }}"
    state: absent
  when: stack_shutdown_remove_media_volume|bool
