---

# Update a deployed stack version.
# Here we rely on everything having already been deployed,
# all we do is the simplest (fastest) that has to be done - and that
# is to alter the stack application...

- include_tasks: prep.yaml

- name: Include sensitive variables
  include_vars:
    file: sensitive.vault
  when: stack_include_sensitive|bool

- name: Deploy stack
  k8s:
    definition: "{{ lookup('template', item) }}"
    host: "{{ k8s_auth_host }}"
    api_key: "{{ k8s_auth_api_key }}"
    validate_certs: "{{ k8s_auth_verify_ssl|default('no', true) }}"
  loop:
  - deployment-beat.yaml.j2
  - statefulset-worker.yaml.j2
  - statefulset-stack.yaml.j2
