---

# To 'wipe' we remove: -
# - Stack
# - Redis
# - Django secret
# - Database
# And then, unconditionally delete: -
# - Database volume
# - Media volume

- name: Set django secret fact
  # These facts are required to remove the secret...
  set_fact:
    stack_django_secret_key_fact: '{{ stack_django_secret_key }}'
    stack_django_superuser_password_fact: '{{ stack_django_superuser_password }}'

- name: Shutdown stack, and redis
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    state: absent
  loop:
  - statefulset-stack
  - statefulset-worker
  - deployment-beat
  - deployment-redis
  - secret-django

- name: Pause before wait (4 Seconds)
  pause:
    seconds: 4

- name: Wait for stack to disappear
  k8s_info:
    kind: Pod
    name: stack-0
    namespace: "{{ stack_namespace }}"
  register: stack_result
  until: stack_result.resources|length == 0
  delay: 8
  retries: "{{ (wait_timeout|int / 8)|int }}"

- name: Pause before wait (4 Seconds)
  pause:
    seconds: 4

- name: Wait for worker to disappear
  k8s_info:
    kind: Pod
    name: worker-0
    namespace: "{{ stack_namespace }}"
  register: worker_result
  until: worker_result.resources|length == 0
  delay: 8
  retries: "{{ (wait_timeout|int / 8)|int }}"

- name: Remove media volume
  k8s:
    definition: "{{ lookup('template', 'pvc-media.yaml.j2') }}"
    state: absent
  when: stack_shutdown_remove_media_volume|bool

- name: Shutdown database
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    state: absent
  loop:
  - statefulset-database

- name: Pause before wait (4 Seconds)
  pause:
    seconds: 4

- name: Wait for database to disappear
  k8s_info:
    kind: Pod
    name: database-0
    namespace: "{{ stack_namespace }}"
  register: db_result
  until: db_result.resources|length == 0
  delay: 8
  retries: "{{ (wait_timeout|int / 8)|int }}"

- name: Remove database volume
  k8s:
    definition: "{{ lookup('template', 'pvc-database.yaml.j2') }}"
    state: absent
  when: stack_shutdown_remove_database_volume|bool
