---

# A play that can be used to check Pods in a given cluster for
# read-only filesystem issues. The play uses a map of volumes
# and the Pods that use them. The play will attempt to write
# to the volume, reporting any that cannot be touched.
#
# You can use delete_failed_pods to also delete Pods that fail.

- hosts: 192.168.253.21
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.11
  tasks:
  - name: LS
    command: ls
  - name: PWD
    command: pwd
  - name: ENV
    command: env
  - name: Run check-no-rofs (dev)
    shell: ansible-playbook site-check-no-rofs.yaml -e cluster=dev
    environment:
      KUBECONFIG: ~/.kube/config-dev
      PATH: /home/wmu55374/.local/bin:{{ ansible_env.PATH }}
    args:
      executable: /bin/bash
  - name: Run check-no-rofs (prod)
    shell: ansible-playbook site-check-no-rofs.yaml -e cluster=prod
    environment:
      KUBECONFIG: ~/.kube/config-prod
      PATH: /home/wmu55374/.local/bin:{{ ansible_env.PATH }}
    args:
      executable: /bin/bash
