---

# A play that can be used to check Pods in a given cluster for
# read-only filesystem issues. The play uses a map of volumes
# and the Pods that use them. The play will attempt to write
# to the volume, reporting any that cannot be touched.
#
# You can use delete_failed_pods to also delete Pods that fail.

- hosts: 192.168.253.21
  become: yes
  become_user: wmu55374
  become_method: su
  become_flags: '--login'
  tasks:
  - name: Run check-no-rofs (dev)
    command: ansible-playbook site-check-no-rofs.yaml -e cluster=dev
    environment:
      KUBECONFIG: ~/.kube/config-dev
  - name: Run check-no-rofs (prod)
    command: ansible-playbook site-check-no-rofs.yaml -e cluster=prod
    environment:
      KUBECONFIG: ~/.kube/config-prod
