---

# A play that can be used to check Pods in a given cluster for
# read-only filesystem issues. For this to work we need an Ansible
# that's more recent than the one on AWX. So we create a server
# with a more recent Python and install Ansible 10 on that machine,
# and then simply run 'ansible-playbook' on the remote server.
#
# It also appears that we need to set the PATH on thew remote server
# to include ~/.local/bin. This is because the Ansible 10 installation
# is in the user's home directory and the PATH is not set to include it.

- hosts: 192.168.253.21
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.11
  tasks:
  - name: Run check-no-rofs (dev)
    command: ansible-playbook site-check-no-rofs.yaml -e cluster=dev
    environment:
      KUBECONFIG: /home/wmu55374/.kube/config-dev
      PATH: /home/wmu55374/.local/bin:{{ ansible_env.PATH }}
    args:
      chdir: fragalysis-stack-kubernetes
  - name: Run check-no-rofs (prod)
    command: ansible-playbook site-check-no-rofs.yaml -e cluster=prod
    environment:
      KUBECONFIG: /home/wmu55374/.kube/config-prod
      PATH: /home/wmu55374/.local/bin:{{ ansible_env.PATH }}
    args:
      chdir: fragalysis-stack-kubernetes
