---

# A play that can be used to check Pods in a given cluster for
# read-only filesystem issues. The play uses a map of volumes
# and the Pods that use them. The play will attempt to write
# to the volume, reporting any that cannot be touched.
#
# You can use delete_failed_pods to also delete Pods that fail.

- hosts: 192.168.253.21
  tasks:
  - name: Run check-no-rofs (dev)
    shell: source /home/wmu55374/.bashrc && ansible-playbook site-check-no-rofs.yaml -e cluster=dev
    environment:
      KUBECONFIG: ~/.kube/config-dev
    args:
      executable: /bin/bash
  - name: Run check-no-rofs (prod)
    shell: source /home/wmu55374/.bashrc && ansible-playbook site-check-no-rofs.yaml -e cluster=prod
    environment:
      KUBECONFIG: ~/.kube/config-prod
    args:
      executable: /bin/bash
