---

# A play that can be used to check application URLS.
# The play uses a map of names and URLs.
# The play will attempt to GET from the URLs, expecting success.

- hosts: localhost
  connection: local
  tasks:
  - name: Check applications
    include_role:
      name: check-applications
