---

# Iterates through the list of volumes
# based on the cluster 'name'.
# If there are failures (at the end) the playbook fails.

- name: Check cluster name
  assert:
    that:
    - cluster != 'SetMe'
    - volumes[cluster] is defined

- name: Reset failed volumes fact
  set_fact:
    failed_volumes: []

- name: Check volume
  include_tasks: check-volume.yaml
  loop: "{{ volumes[cluster] }}"
  no_log: True

- name: Handle failed volumes
  block:

  - name: Display failed volumes fact
    debug:
      var: failed_volumes

  - name: Assert no failed volumes
    fail:
      msg: "There are failed volumes: {{ failed_volumes }}"

  when: failed_volumes | length > 0
