---

# You might run this play on a single host with: -
#
#   ansible-playbook playbooks/sysstat.yaml --limit 192.168.253.132

- name: sysstat utility management
  hosts: all
  become: true
  vars:
    sysstat_state: present
    sysstat_history: 28

  tasks:
  - name: Install sysstat tool
    when: sysstat_state == 'present'
    block:

    - name: Install sysstat
      ansible.builtin.apt:
        name: sysstat

    - name: Configure sysstat (enabled)
      ansible.builtin.lineinfile:
        path: /etc/default/sysstat
        regexp: '^ENABLED='
        line: ENABLED="true"

    - name: Configure sysstat (history)
      ansible.builtin.lineinfile:
        path: /etc/default/sysstat
        regexp: '^HISTORY='
        line: HISTORY={{ sysstat_history }}

    - name: Start sysstat
      ansible.builtin.service:
        name: sysstat
        enabled: true
        state: started
      when: sysstat_state == 'present'

  - name: Remove sysstat tool
    when: sysstat_state != 'present'
    block:

    - name: Remove sysstat
      ansible.builtin.apt:
        name: sysstat
        state: absent
