---
namespaceOverride: monitoring
prometheusOperator:
  priorityClassName: im-application-critical
prometheus:
  prometheusSpec:
    priorityClassName: im-application-critical
    additionalScrapeConfigs:
    - job_name: staging-stack
      scheme: https
      scrape_interval: 5s
      static_configs:
      - targets:
        - fragalysis.xchem.diamond.ac.uk
        labels:
          app: staging
    - job_name: v2-production-stack
      scheme: https
      scrape_interval: 5s
      static_configs:
      - targets:
        - fragalysis.diamond.ac.uk
        labels:
          app: production
prometheus-node-exporter:
  namespaceOverride: monitoring
thanosRuler:
  thanosRulerSpec:
    priorityClassName: im-application-critical
alertmanager:
  namespaceOverride: monitoring
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-nginx-production
      kubernetes.io/tls-acme: "true"
    hosts:
    - alartmanager.xchem.diamond.ac.uk
    tls:
    - secretName: alartmanager-general-tls
      hosts:
      - alartmanager.xchem.diamond.ac.uk
  alertmanagerSpec:
    priorityClassName: im-application-critical
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: csi-cinder-sc-delete
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
grafana:
  namespaceOverride: monitoring
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-nginx-production
      kubernetes.io/tls-acme: "true"
    hosts:
    - grafana.xchem.diamond.ac.uk
    tls:
    - secretName: grafana-general-tls
      hosts:
      - grafana.xchem.diamond.ac.uk
  persistence:
    enabled: true
    type: pvc
    accessModes:
    - ReadWriteOnce
    size: 10Gi
    storageClassName: csi-cinder-sc-delete
