---

- name: Include sensitive variables
  include_vars:
    file: sensitive.vault

# Create the namespace (project) and other key bits.
# Everything, except the graph at the moment goes into
# a dedicated namespace. When done we simply delete the namespace.

- name: Check the namespace
  assert:
    that:
    - taa_namespace | string | length > 0

- name: Creating namespace '{{ taa_namespace }}'
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - namespace
  - serviceaccount

- name: Deploy SSH Private Key
  k8s:
    definition: "{{ lookup('template', 'configmap-ssh-key.yaml.j2') }}"
    wait: yes
  when:
  - taa_ssh_private_key | string | length != 0

- name: Check keys secret
  k8s_info:
    kind: Secret
    api_version: v1
    namespace: "{{ taa_namespace }}"
    name: keys
  register: s_result

- name: Set (new) keys secret
  block:

  - name: Write keys secret
    k8s:
      definition: "{{ lookup('template', 'secret.yaml.j2') }}"
      wait: yes

  when: s_result.resources|length == 0

- name: Deploy authenticator
  k8s:
    definition: "{{ lookup('template', item) }}"
    wait: yes
  loop:
  - deployment.yaml.j2
  - service-auth.yaml.j2

- name: Deploy authenticator stats Ingress
  k8s:
    definition: "{{ lookup('template', item) }}"
    wait: yes
  loop:
  - service-stats.yaml.j2
  - ingress-stats.yaml.j2
  when: taa_stats_url | string | length > 0
