---

# Attempt to access the application URL.
# If it's a 'status' endpoint then inspect the status result.

- name: Display application
  debug:
    var: item

- name: Check URI Response
  ansible.builtin.uri:
    url: "{{ item.url }}"
    timeout: 4
    validate_certs: "{{ item.validate_certs | default(false) | bool}}"
    return_content: true
  register: url_result
  ignore_errors: yes

#- name: Display URI Response
#  debug:
#    var: url_result

# We have to reset the service state fact,
# this may have been set on a previous iteration.
- name: Reset service state fact
  set_fact:
    fs_service_state: []

- name: Reset service_errors fact
  set_fact:
    status_errors: []

# Is the URL a service state endpoint?
# If so we inspect the service response to make sure
# they're either OK or NOT_CONFIGURED
- name: Get service state from response
  when:
  - item.type is defined
  - item.type == 'fs-service-state'
  block:

  - name: Extract service name and state from response
    set_fact:
      fs_service_state: "{{ url_result.json | json_query('service_states[*].{name: name, state: state}') }}"
    when: url_result.json is defined

  - name: Set status error if something's not OK and NOT_DEFINED
    set_fact:
      status_errors: "{{ status_errors + [{'name': service_state.name, 'state': service_state.state}] }}"
    loop: "{{ fs_service_state }}"
    loop_control:
      loop_var: service_state
    when: service_state is not defined or service_state.state not in ['OK', 'NOT_CONFIGURED']

  - name: Display service errors
    debug:
      var: status_errors
    when: status_errors | length > 0

  - name: Add status errors to item
    set_fact:
      item: "{{ item | combine({'status_errors': status_errors}) }}"
    when: status_errors | length > 0

  - name: Display item
    debug:
      var: item
    when: status_errors | length > 0

- name: Add failure to failed_applications list
  set_fact:
    failed_applications: "{{ failed_applications + [item] }}"
  when: url_result.failed or status_errors | length > 0
